/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author Ayler
 */
public class AdminHomeViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminHomeViewSwing.class.getName());

    /**
     * Creates new form AdminHomeViewSwing
     */
    public AdminHomeViewSwing() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(false);
         configurarRodape();
    }
    
   private void configurarRodape() {
  
    getContentPane().removeAll();


    getContentPane().setLayout(new java.awt.BorderLayout());


    javax.swing.JPanel rodape = new javax.swing.JPanel(
            new java.awt.BorderLayout()
    );

 
    java.awt.Font fonteAtual = txtUserLog.getFont();
    txtUserLog.setFont(
            new java.awt.Font(
                    fonteAtual.getName(),
                    java.awt.Font.BOLD,   // NEGRITO
                    fonteAtual.getSize() + 2 // um pouco maior
            )
    );

    txtUserLog.setEditable(false);
    txtUserLog.setBorder(
            javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12)
    );

    rodape.add(txtUserLog, java.awt.BorderLayout.CENTER);

   
    getContentPane().add(rodape, java.awt.BorderLayout.SOUTH);

    revalidate();
    repaint();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        txtUserLog = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastarUsuarioAdmin = new javax.swing.JMenu();
        mnuCadastrar = new javax.swing.JMenuItem();
        mnuAutorizar = new javax.swing.JMenuItem();
        mnuNotificacaoAdmin = new javax.swing.JMenu();
        itemCadastrarNotificacao = new javax.swing.JMenuItem();
        mnuEstatistica = new javax.swing.JMenu();
        mnuNotficacaoEstatistica = new javax.swing.JMenuItem();
        mnuConfigurarLogAdmin = new javax.swing.JMenu();
        mnuLog = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCadastarUsuarioAdmin.setText("Usuario");
        mnuCadastarUsuarioAdmin.setDelay(0);

        mnuCadastrar.setText("Cadastrar");
        mnuCadastarUsuarioAdmin.add(mnuCadastrar);

        mnuAutorizar.setText("Autorizar");
        mnuCadastarUsuarioAdmin.add(mnuAutorizar);

        jMenuBar1.add(mnuCadastarUsuarioAdmin);

        mnuNotificacaoAdmin.setText("Enviar Notificação");
        mnuNotificacaoAdmin.setDelay(0);

        itemCadastrarNotificacao.setText("Registrar Notificação");
        itemCadastrarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarNotificacaoActionPerformed(evt);
            }
        });
        mnuNotificacaoAdmin.add(itemCadastrarNotificacao);

        jMenuBar1.add(mnuNotificacaoAdmin);

        mnuEstatistica.setText("Estatísticas ");

        mnuNotficacaoEstatistica.setText("Notificações");
        mnuNotficacaoEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNotficacaoEstatisticaActionPerformed(evt);
            }
        });
        mnuEstatistica.add(mnuNotficacaoEstatistica);

        jMenuBar1.add(mnuEstatistica);

        mnuConfigurarLogAdmin.setText("Configurar Log");
        mnuConfigurarLogAdmin.setDelay(0);

        mnuLog.setText("Log");
        mnuLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogActionPerformed(evt);
            }
        });
        mnuConfigurarLogAdmin.add(mnuLog);

        jMenuBar1.add(mnuConfigurarLogAdmin);

        btnSair.setText("Sair");

        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        btnSair.add(mnuLogout);

        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(txtUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCadastrarNotificacaoActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuNotficacaoEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNotficacaoEstatisticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNotficacaoEstatisticaActionPerformed

    private void mnuLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminHomeViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuItem itemCadastrarNotificacao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuAutorizar;
    private javax.swing.JMenu mnuCadastarUsuarioAdmin;
    private javax.swing.JMenuItem mnuCadastrar;
    private javax.swing.JMenu mnuConfigurarLogAdmin;
    private javax.swing.JMenu mnuEstatistica;
    private javax.swing.JMenuItem mnuLog;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuNotficacaoEstatistica;
    private javax.swing.JMenu mnuNotificacaoAdmin;
    private javax.swing.JTextField txtUserLog;
    // End of variables declaration//GEN-END:variables

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }


    public JMenu getMnuCadastarUsuarioAdmin() {
        return mnuCadastarUsuarioAdmin;
    }

    public void setMnuCadastarUsuarioAdmin(JMenu mnuCadastarUsuarioAdmin) {
        this.mnuCadastarUsuarioAdmin = mnuCadastarUsuarioAdmin;
    }

    public JMenu getMnuConfigurarLogAdmin() {
        return mnuConfigurarLogAdmin;
    }

    public void setMnuConfigurarLogAdmin(JMenu mnuConfigurarLogAdmin) {
        this.mnuConfigurarLogAdmin = mnuConfigurarLogAdmin;
    }

    public JMenu getMnuNotificacaoAdmin() {
        return mnuNotificacaoAdmin;
    }

    public void setMnuNotificacaoAdmin(JMenu mnuNotificacaoAdmin) {
        this.mnuNotificacaoAdmin = mnuNotificacaoAdmin;
    }
    
    public JMenuItem getItemEnviarNotificacao() {
    return itemCadastrarNotificacao;
}
    
public JMenuItem getItemCadastrarNotificacao() {
    return itemCadastrarNotificacao;
}

    public JMenu getBtnSair() {
        return btnSair;
    }

    public void setBtnSair(JMenu btnSair) {
        this.btnSair = btnSair;
    }

    public JMenuItem getMnuLogout() {
        return mnuLogout;
    }

    public void setMnuLogout(JMenuItem mnuLogout) {
        this.mnuLogout = mnuLogout;
    }

    public JMenuItem getMnuAutorizar() {
        return mnuAutorizar;
    }

    public void setMnuAutorizar(JMenuItem mnuAutorizar) {
        this.mnuAutorizar = mnuAutorizar;
    }

    public JMenuItem getMnuCadastrar() {
        return mnuCadastrar;
    }

    public void setMnuCadastrar(JMenuItem mnuCadastrar) {
        this.mnuCadastrar = mnuCadastrar;
    }


    public JMenu getMnuEstatistica() {
        return mnuEstatistica;
    }

    public void setMnuEstatistica(JMenu mnuEstatistica) {
        this.mnuEstatistica = mnuEstatistica;
    }

    public JMenuItem getMnuNotficacaoEstatistica() {
        return mnuNotficacaoEstatistica;
    }

    public void setMnuNotficacaoEstatistica(JMenuItem mnuNotficacaoEstatistica) {
        this.mnuNotficacaoEstatistica = mnuNotficacaoEstatistica;
    }

    public JTextField getTxtUserLog() {
        return txtUserLog;
    }

    public void setTxtUserLog(JTextField txtUserLog) {
        this.txtUserLog = txtUserLog;
    }

    public JMenuItem getMnuLog() {
        return mnuLog;
    }

    public void setMnuLog(JMenuItem mnuLog) {
        this.mnuLog = mnuLog;
    }

    

}
