/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Ayler
 */
public class AdminHomeViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminHomeViewSwing.class.getName());

    /**
     * Creates new form AdminHomeViewSwing
     */
    public AdminHomeViewSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemvindo = new javax.swing.JLabel();
        lblNomeUsuarioAdmin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastarUsuarioAdmin = new javax.swing.JMenu();
        mnuAutorizarUsuariosAdmin = new javax.swing.JMenu();
        mnuListarUsuariosAdmin = new javax.swing.JMenu();
        mnuNotificacaoAdmin = new javax.swing.JMenu();
        mnuConfigurarLogAdmin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBemvindo.setText("Bem vindo !");

        lblNomeUsuarioAdmin.setText("Nome do cara");

        mnuCadastarUsuarioAdmin.setText("Cadastrar Usuário");
        jMenuBar1.add(mnuCadastarUsuarioAdmin);

        mnuAutorizarUsuariosAdmin.setText("Autorizar Usuários");
        jMenuBar1.add(mnuAutorizarUsuariosAdmin);

        mnuListarUsuariosAdmin.setText("Listar Usuários");
        jMenuBar1.add(mnuListarUsuariosAdmin);

        mnuNotificacaoAdmin.setText("Enviar Notificação");
        jMenuBar1.add(mnuNotificacaoAdmin);

        mnuConfigurarLogAdmin.setText("Configurar Log");
        jMenuBar1.add(mnuConfigurarLogAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(lblBemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeUsuarioAdmin))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminHomeViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBemvindo;
    private javax.swing.JLabel lblNomeUsuarioAdmin;
    private javax.swing.JMenu mnuAutorizarUsuariosAdmin;
    private javax.swing.JMenu mnuCadastarUsuarioAdmin;
    private javax.swing.JMenu mnuConfigurarLogAdmin;
    private javax.swing.JMenu mnuListarUsuariosAdmin;
    private javax.swing.JMenu mnuNotificacaoAdmin;
    // End of variables declaration//GEN-END:variables
}
