/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Ayler
 */
public class AdminHomeViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminHomeViewSwing.class.getName());

    /**
     * Creates new form AdminHomeViewSwing
     */
    public AdminHomeViewSwing() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemvindo = new javax.swing.JLabel();
        lblNomeUsuarioAdmin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastarUsuarioAdmin = new javax.swing.JMenu();
        mnuAutorizarUsuariosAdmin = new javax.swing.JMenu();
        mnuNotificacaoAdmin = new javax.swing.JMenu();
        itemCadastrarNotificacao = new javax.swing.JMenuItem();
        mnuConfigurarLogAdmin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBemvindo.setText("Bem vindo !");

        lblNomeUsuarioAdmin.setText("Nome do cara");

        mnuCadastarUsuarioAdmin.setText("Cadastrar Usuário");
        mnuCadastarUsuarioAdmin.setDelay(0);
        jMenuBar1.add(mnuCadastarUsuarioAdmin);

        mnuAutorizarUsuariosAdmin.setText("Autorizar Usuários");
        mnuAutorizarUsuariosAdmin.setDelay(0);
        jMenuBar1.add(mnuAutorizarUsuariosAdmin);

        mnuNotificacaoAdmin.setText("Enviar Notificação");
        mnuNotificacaoAdmin.setDelay(0);

        itemCadastrarNotificacao.setText("Registrar Notificação");
        itemCadastrarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarNotificacaoActionPerformed(evt);
            }
        });
        mnuNotificacaoAdmin.add(itemCadastrarNotificacao);

        jMenuBar1.add(mnuNotificacaoAdmin);

        mnuConfigurarLogAdmin.setText("Configurar Log");
        mnuConfigurarLogAdmin.setDelay(0);
        jMenuBar1.add(mnuConfigurarLogAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(lblBemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeUsuarioAdmin))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCadastrarNotificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminHomeViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCadastrarNotificacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBemvindo;
    private javax.swing.JLabel lblNomeUsuarioAdmin;
    private javax.swing.JMenu mnuAutorizarUsuariosAdmin;
    private javax.swing.JMenu mnuCadastarUsuarioAdmin;
    private javax.swing.JMenu mnuConfigurarLogAdmin;
    private javax.swing.JMenu mnuNotificacaoAdmin;
    // End of variables declaration//GEN-END:variables

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JLabel getLblBemvindo() {
        return lblBemvindo;
    }

    public void setLblBemvindo(JLabel lblBemvindo) {
        this.lblBemvindo = lblBemvindo;
    }

    public JLabel getLblNomeUsuarioAdmin() {
        return lblNomeUsuarioAdmin;
    }

    public void setLblNomeUsuarioAdmin(JLabel lblNomeUsuarioAdmin) {
        this.lblNomeUsuarioAdmin = lblNomeUsuarioAdmin;
    }

    public JMenu getMnuAutorizarUsuariosAdmin() {
        return mnuAutorizarUsuariosAdmin;
    }

    public void setMnuAutorizarUsuariosAdmin(JMenu mnuAutorizarUsuariosAdmin) {
        this.mnuAutorizarUsuariosAdmin = mnuAutorizarUsuariosAdmin;
    }

    public JMenu getMnuCadastarUsuarioAdmin() {
        return mnuCadastarUsuarioAdmin;
    }

    public void setMnuCadastarUsuarioAdmin(JMenu mnuCadastarUsuarioAdmin) {
        this.mnuCadastarUsuarioAdmin = mnuCadastarUsuarioAdmin;
    }

    public JMenu getMnuConfigurarLogAdmin() {
        return mnuConfigurarLogAdmin;
    }

    public void setMnuConfigurarLogAdmin(JMenu mnuConfigurarLogAdmin) {
        this.mnuConfigurarLogAdmin = mnuConfigurarLogAdmin;
    }

    public JMenu getMnuNotificacaoAdmin() {
        return mnuNotificacaoAdmin;
    }

    public void setMnuNotificacaoAdmin(JMenu mnuNotificacaoAdmin) {
        this.mnuNotificacaoAdmin = mnuNotificacaoAdmin;
    }
    
    public JMenuItem getItemEnviarNotificacao() {
    return itemCadastrarNotificacao;
}
    
public JMenuItem getItemCadastrarNotificacao() {
    return itemCadastrarNotificacao;
}

}
