/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author Ayler
 */
public class AlterarSenhaViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlterarSenhaViewSwing.class.getName());

    /**
     * Creates new form AlterarSenhaViewSwing
     */
    public AlterarSenhaViewSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        psswAlterarSenhaAtual = new javax.swing.JPasswordField();
        psswAlterarSenhaNova = new javax.swing.JPasswordField();
        btnAlterarSenhaAlterarSenha = new javax.swing.JButton();
        lblAlterarSenhaSenhaAtual = new javax.swing.JLabel();
        lblAlterarSenhaNovaSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        psswAlterarSenhaAtual.setText("jPasswordField1");

        psswAlterarSenhaNova.setText("jPasswordField2");

        btnAlterarSenhaAlterarSenha.setText("Alterar Senha");

        lblAlterarSenhaSenhaAtual.setText("Senha Atual");

        lblAlterarSenhaNovaSenha.setText("Nova Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(psswAlterarSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(btnAlterarSenhaAlterarSenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlterarSenhaNovaSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAlterarSenhaSenhaAtual)
                                .addGap(27, 27, 27)
                                .addComponent(psswAlterarSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psswAlterarSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlterarSenhaSenhaAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psswAlterarSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlterarSenhaNovaSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarSenhaAlterarSenha)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlterarSenhaViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenhaAlterarSenha;
    private javax.swing.JLabel lblAlterarSenhaNovaSenha;
    private javax.swing.JLabel lblAlterarSenhaSenhaAtual;
    private javax.swing.JPasswordField psswAlterarSenhaAtual;
    private javax.swing.JPasswordField psswAlterarSenhaNova;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAlterarSenhaAlterarSenha() {
        return btnAlterarSenhaAlterarSenha;
    }

    public void setBtnAlterarSenhaAlterarSenha(JButton btnAlterarSenhaAlterarSenha) {
        this.btnAlterarSenhaAlterarSenha = btnAlterarSenhaAlterarSenha;
    }

    public JLabel getLblAlterarSenhaNovaSenha() {
        return lblAlterarSenhaNovaSenha;
    }

    public void setLblAlterarSenhaNovaSenha(JLabel lblAlterarSenhaNovaSenha) {
        this.lblAlterarSenhaNovaSenha = lblAlterarSenhaNovaSenha;
    }

    public JLabel getLblAlterarSenhaSenhaAtual() {
        return lblAlterarSenhaSenhaAtual;
    }

    public void setLblAlterarSenhaSenhaAtual(JLabel lblAlterarSenhaSenhaAtual) {
        this.lblAlterarSenhaSenhaAtual = lblAlterarSenhaSenhaAtual;
    }

    public JPasswordField getPsswAlterarSenhaAtual() {
        return psswAlterarSenhaAtual;
    }

    public void setPsswAlterarSenhaAtual(JPasswordField psswAlterarSenhaAtual) {
        this.psswAlterarSenhaAtual = psswAlterarSenhaAtual;
    }

    public JPasswordField getPsswAlterarSenhaNova() {
        return psswAlterarSenhaNova;
    }

    public void setPsswAlterarSenhaNova(JPasswordField psswAlterarSenhaNova) {
        this.psswAlterarSenhaNova = psswAlterarSenhaNova;
    }
}
