/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author lukian.borges
 */
public class AlterarSenhaViewSwing extends javax.swing.JPanel {

    /**
     * Creates new form AlterarSenhaViewSwing
     */
    public AlterarSenhaViewSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        psswAlterarSenhaAtual = new javax.swing.JPasswordField();
        psswAlterarSenhaNova = new javax.swing.JPasswordField();
        btnAlterarSenhaAlterarSenha1 = new javax.swing.JButton();
        lblAlterarSenhaSenhaAtual1 = new javax.swing.JLabel();
        lblAlterarSenhaNovaSenha2 = new javax.swing.JLabel();
        lblAlterarSenhaNovaSenha3 = new javax.swing.JLabel();
        psswAlterarSenhaConfirma = new javax.swing.JPasswordField();

        psswAlterarSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswAlterarSenhaAtualActionPerformed(evt);
            }
        });

        btnAlterarSenhaAlterarSenha1.setText("Alterar Senha");

        lblAlterarSenhaSenhaAtual1.setText("Senha Atual");

        lblAlterarSenhaNovaSenha2.setText("Nova Senha");

        lblAlterarSenhaNovaSenha3.setText("Confirmar Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlterarSenhaNovaSenha3)
                            .addComponent(lblAlterarSenhaSenhaAtual1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAlterarSenhaNovaSenha2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(psswAlterarSenhaNova, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(psswAlterarSenhaAtual)
                            .addComponent(psswAlterarSenhaConfirma)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnAlterarSenhaAlterarSenha1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlterarSenhaSenhaAtual1)
                    .addComponent(psswAlterarSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlterarSenhaNovaSenha2)
                    .addComponent(psswAlterarSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlterarSenhaNovaSenha3)
                    .addComponent(psswAlterarSenhaConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnAlterarSenhaAlterarSenha1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void psswAlterarSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswAlterarSenhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswAlterarSenhaAtualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenhaAlterarSenha1;
    private javax.swing.JLabel lblAlterarSenhaNovaSenha2;
    private javax.swing.JLabel lblAlterarSenhaNovaSenha3;
    private javax.swing.JLabel lblAlterarSenhaSenhaAtual1;
    private javax.swing.JPasswordField psswAlterarSenhaAtual;
    private javax.swing.JPasswordField psswAlterarSenhaConfirma;
    private javax.swing.JPasswordField psswAlterarSenhaNova;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAlterarSenhaAlterarSenha1() {
        return btnAlterarSenhaAlterarSenha1;
    }

    public void setBtnAlterarSenhaAlterarSenha1(JButton btnAlterarSenhaAlterarSenha1) {
        this.btnAlterarSenhaAlterarSenha1 = btnAlterarSenhaAlterarSenha1;
    }

    public JLabel getLblAlterarSenhaNovaSenha2() {
        return lblAlterarSenhaNovaSenha2;
    }

    public void setLblAlterarSenhaNovaSenha2(JLabel lblAlterarSenhaNovaSenha2) {
        this.lblAlterarSenhaNovaSenha2 = lblAlterarSenhaNovaSenha2;
    }

    public JLabel getLblAlterarSenhaNovaSenha3() {
        return lblAlterarSenhaNovaSenha3;
    }

    public void setLblAlterarSenhaNovaSenha3(JLabel lblAlterarSenhaNovaSenha3) {
        this.lblAlterarSenhaNovaSenha3 = lblAlterarSenhaNovaSenha3;
    }

    public JLabel getLblAlterarSenhaSenhaAtual1() {
        return lblAlterarSenhaSenhaAtual1;
    }

    public void setLblAlterarSenhaSenhaAtual1(JLabel lblAlterarSenhaSenhaAtual1) {
        this.lblAlterarSenhaSenhaAtual1 = lblAlterarSenhaSenhaAtual1;
    }

    public JPasswordField getPsswAlterarSenhaAtual() {
        return psswAlterarSenhaAtual;
    }

    public void setPsswAlterarSenhaAtual(JPasswordField psswAlterarSenhaAtual) {
        this.psswAlterarSenhaAtual = psswAlterarSenhaAtual;
    }

    public JPasswordField getPsswAlterarSenhaConfirma() {
        return psswAlterarSenhaConfirma;
    }

    public void setPsswAlterarSenhaConfirma(JPasswordField psswAlterarSenhaConfirma) {
        this.psswAlterarSenhaConfirma = psswAlterarSenhaConfirma;
    }

    public JPasswordField getPsswAlterarSenhaNova() {
        return psswAlterarSenhaNova;
    }

    public void setPsswAlterarSenhaNova(JPasswordField psswAlterarSenhaNova) {
        this.psswAlterarSenhaNova = psswAlterarSenhaNova;
    }





}
