/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Ayler
 */
public class ConfiguracaoLogViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfiguracaoLogViewSwing.class.getName());

    /**
     * Creates new form ConfiguracaoLogViewSwing
     */
    public ConfiguracaoLogViewSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radConfiguracaoLogCSV = new javax.swing.JRadioButton();
        radConfiguracaoLogJSONL = new javax.swing.JRadioButton();
        btnConfiguracaoLogSalvar = new javax.swing.JButton();
        lblConfiguracaoEscolhaOLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radConfiguracaoLogCSV.setText("CSV");

        radConfiguracaoLogJSONL.setText("JSONL");

        btnConfiguracaoLogSalvar.setText("Salvar");

        lblConfiguracaoEscolhaOLog.setText("Escolha como deve sair o Log:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfiguracaoEscolhaOLog)
                    .addComponent(btnConfiguracaoLogSalvar)
                    .addComponent(radConfiguracaoLogJSONL)
                    .addComponent(radConfiguracaoLogCSV))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblConfiguracaoEscolhaOLog)
                .addGap(18, 18, 18)
                .addComponent(radConfiguracaoLogCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radConfiguracaoLogJSONL)
                .addGap(18, 18, 18)
                .addComponent(btnConfiguracaoLogSalvar)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfiguracaoLogViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracaoLogSalvar;
    private javax.swing.JLabel lblConfiguracaoEscolhaOLog;
    private javax.swing.JRadioButton radConfiguracaoLogCSV;
    private javax.swing.JRadioButton radConfiguracaoLogJSONL;
    // End of variables declaration//GEN-END:variables
}
