/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author lukian.borges
 */
public class ConfiguracaoLogViewSwing extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracaoLogViewSwing
     */
    public ConfiguracaoLogViewSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radConfiguracaoLogCSV = new javax.swing.JRadioButton();
        radConfiguracaoLogJSONL = new javax.swing.JRadioButton();
        btnConfiguracaoLogSalvar = new javax.swing.JButton();
        lblConfiguracaoEscolhaOLog = new javax.swing.JLabel();

        radConfiguracaoLogCSV.setText("CSV");

        radConfiguracaoLogJSONL.setText("JSONL");

        btnConfiguracaoLogSalvar.setText("Salvar");

        lblConfiguracaoEscolhaOLog.setText("Escolha como deve sair o Log:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfiguracaoEscolhaOLog)
                    .addComponent(btnConfiguracaoLogSalvar)
                    .addComponent(radConfiguracaoLogJSONL)
                    .addComponent(radConfiguracaoLogCSV))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblConfiguracaoEscolhaOLog)
                .addGap(18, 18, 18)
                .addComponent(radConfiguracaoLogCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radConfiguracaoLogJSONL)
                .addGap(18, 18, 18)
                .addComponent(btnConfiguracaoLogSalvar)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracaoLogSalvar;
    private javax.swing.JLabel lblConfiguracaoEscolhaOLog;
    private javax.swing.JRadioButton radConfiguracaoLogCSV;
    private javax.swing.JRadioButton radConfiguracaoLogJSONL;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnConfiguracaoLogSalvar() {
        return btnConfiguracaoLogSalvar;
    }

    public void setBtnConfiguracaoLogSalvar(JButton btnConfiguracaoLogSalvar) {
        this.btnConfiguracaoLogSalvar = btnConfiguracaoLogSalvar;
    }

    public JLabel getLblConfiguracaoEscolhaOLog() {
        return lblConfiguracaoEscolhaOLog;
    }

    public void setLblConfiguracaoEscolhaOLog(JLabel lblConfiguracaoEscolhaOLog) {
        this.lblConfiguracaoEscolhaOLog = lblConfiguracaoEscolhaOLog;
    }

    public JRadioButton getRadConfiguracaoLogCSV() {
        return radConfiguracaoLogCSV;
    }

    public void setRadConfiguracaoLogCSV(JRadioButton radConfiguracaoLogCSV) {
        this.radConfiguracaoLogCSV = radConfiguracaoLogCSV;
    }

    public JRadioButton getRadConfiguracaoLogJSONL() {
        return radConfiguracaoLogJSONL;
    }

    public void setRadConfiguracaoLogJSONL(JRadioButton radConfiguracaoLogJSONL) {
        this.radConfiguracaoLogJSONL = radConfiguracaoLogJSONL;
    }



}
