/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author Ayler
 */
public class EnviarNotificacaoViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnviarNotificacaoViewSwing.class.getName());

    /**
     * Creates new form EnviarNotificacaoViewSwing
     */
    public EnviarNotificacaoViewSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarioNotificacao = new javax.swing.JComboBox<>();
        lblUsuarioNotificacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaMensagemNotificacao = new javax.swing.JTextArea();
        btnEnviarNotificacao = new javax.swing.JToggleButton();
        lblMensagemNotificacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbUsuarioNotificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario 1", "Usuario 2" }));
        cmbUsuarioNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioNotificacaoActionPerformed(evt);
            }
        });

        lblUsuarioNotificacao.setText("Usuário:");

        txtaMensagemNotificacao.setColumns(20);
        txtaMensagemNotificacao.setRows(5);
        jScrollPane1.setViewportView(txtaMensagemNotificacao);

        btnEnviarNotificacao.setText("Enviar Notificação");
        btnEnviarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarNotificacaoActionPerformed(evt);
            }
        });

        lblMensagemNotificacao.setText("Mensagem: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnviarNotificacao)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagemNotificacao)
                            .addComponent(lblUsuarioNotificacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUsuarioNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsuarioNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioNotificacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensagemNotificacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarNotificacao)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarNotificacaoActionPerformed

    private void cmbUsuarioNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuarioNotificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnviarNotificacaoViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEnviarNotificacao;
    private javax.swing.JComboBox<String> cmbUsuarioNotificacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagemNotificacao;
    private javax.swing.JLabel lblUsuarioNotificacao;
    private javax.swing.JTextArea txtaMensagemNotificacao;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getBtnEnviarNotificacao() {
        return btnEnviarNotificacao;
    }

    public void setBtnEnviarNotificacao(JToggleButton btnEnviarNotificacao) {
        this.btnEnviarNotificacao = btnEnviarNotificacao;
    }

    public JComboBox<String> getCmbUsuarioNotificacao() {
        return cmbUsuarioNotificacao;
    }

    public void setCmbUsuarioNotificacao(JComboBox<String> cmbUsuarioNotificacao) {
        this.cmbUsuarioNotificacao = cmbUsuarioNotificacao;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblMensagemNotificacao() {
        return lblMensagemNotificacao;
    }

    public void setLblMensagemNotificacao(JLabel lblMensagemNotificacao) {
        this.lblMensagemNotificacao = lblMensagemNotificacao;
    }

    public JLabel getLblUsuarioNotificacao() {
        return lblUsuarioNotificacao;
    }

    public void setLblUsuarioNotificacao(JLabel lblUsuarioNotificacao) {
        this.lblUsuarioNotificacao = lblUsuarioNotificacao;
    }

    public JTextArea getTxtaMensagemNotificacao() {
        return txtaMensagemNotificacao;
    }

    public void setTxtaMensagemNotificacao(JTextArea txtaMensagemNotificacao) {
        this.txtaMensagemNotificacao = txtaMensagemNotificacao;
    }
}
