/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.awt.Color;



/**
 *
 * @author Ayler
 */
public class LoginViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginViewSwing.class.getName());

    /**
     * Creates new form LoginViewSwing
     */
    public LoginViewSwing() {
    initComponents();

    // === CAMPOS DE TEXTO MODERNOS ===
    txtUsernameField.setOpaque(false);
    txtUsernameField.setBackground(new Color(255, 255, 255));
    txtUsernameField.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new Color(180, 180, 180), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        )
    );

    psswSenhaField.setOpaque(false);
    psswSenhaField.setBackground(new Color(255, 255, 255));
    psswSenhaField.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new Color(180, 180, 180), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        )
    );

    // === BOTÃO LOGIN ===
    btnLogin.setFocusPainted(false);
    btnLogin.setContentAreaFilled(false); 
    btnLogin.setOpaque(true);
    btnLogin.setBackground(new Color(117, 117, 117)); // Azul moderno
    btnLogin.setForeground(Color.WHITE);
    btnLogin.setBorder(
        new javax.swing.border.LineBorder(new Color(33,150,243), 1, true)
    );

    // === BOTÃO SOLICITAR ACESSO ===
    btnSolicitarAcesso.setFocusPainted(false);
    btnSolicitarAcesso.setContentAreaFilled(false);
    btnSolicitarAcesso.setOpaque(true);
    btnSolicitarAcesso.setBackground(new Color(117, 117, 117)); // Cinza moderno
    btnSolicitarAcesso.setForeground(Color.WHITE);
    btnSolicitarAcesso.setBorder(
        new javax.swing.border.LineBorder(new Color(117,117,117), 1, true)
    );
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsernameField = new javax.swing.JTextField();
        psswSenhaField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        lblErro = new javax.swing.JLabel();
        btnSolicitarAcesso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        txtUsernameField.setToolTipText("");
        txtUsernameField.setAlignmentX(0.8F);
        txtUsernameField.setAlignmentY(0.8F);
        txtUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsernameField);
        txtUsernameField.setBounds(129, 83, 160, 30);

        psswSenhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswSenhaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(psswSenhaField);
        psswSenhaField.setBounds(129, 127, 160, 30);

        btnLogin.setText("Login");
        getContentPane().add(btnLogin);
        btnLogin.setBounds(60, 180, 137, 23);

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuário:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(75, 80, 50, 30);

        lblsenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblsenha.setForeground(new java.awt.Color(0, 0, 0));
        lblsenha.setText("Senha:");
        getContentPane().add(lblsenha);
        lblsenha.setBounds(80, 124, 50, 30);
        getContentPane().add(lblErro);
        lblErro.setBounds(228, 173, 0, 23);

        btnSolicitarAcesso.setText("Solicitar Acesso");
        btnSolicitarAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitarAcesso);
        btnSolicitarAcesso.setBounds(220, 180, 137, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/login2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-880, -90, 1620, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitarAcessoActionPerformed

    private void txtUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFieldActionPerformed

    private void psswSenhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswSenhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswSenhaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSolicitarAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JPasswordField psswSenhaField;
    private javax.swing.JTextField txtUsernameField;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    public JLabel getLblErro() {
        return lblErro;
    }

    public void setLblErro(JLabel lblErro) {
        this.lblErro = lblErro;
    }

    public JLabel getLblUsuario() {
        return lblUsuario;
    }

    public void setLblUsuario(JLabel lblUsuario) {
        this.lblUsuario = lblUsuario;
    }

    public JLabel getLblsenha() {
        return lblsenha;
    }

    public void setLblsenha(JLabel lblsenha) {
        this.lblsenha = lblsenha;
    }

    public JPasswordField getPsswSenhaField() {
        return psswSenhaField;
    }

    public void setPsswSenhaField(JPasswordField psswSenhaField) {
        this.psswSenhaField = psswSenhaField;
    }

    public JTextField getTxtUsernameField() {
        return txtUsernameField;
    }

    public void setTxtUsernameField(JTextField txtUsernameField) {
        this.txtUsernameField = txtUsernameField;
    }

    public JButton getBtnSolicitarAcesso() {
        return btnSolicitarAcesso;
    }

    public void setBtnSolicitarAcesso(JButton btnSolicitarAcesso) {
        this.btnSolicitarAcesso = btnSolicitarAcesso;
    }
    
}
