/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;

/**
 *
 * @author Ayler
 */
public class PainelEstatisticas extends javax.swing.JPanel {

    /**
     * Creates new form PainelEstatisticas
     */
    public PainelEstatisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPanelEstatisticasTotalDeUsuarios = new javax.swing.JLabel();
        lblPanelEstatisticasNumeroTotalDeUsuarios = new javax.swing.JLabel();
        lblPanelEstatisticasUsuariosAutorizados = new javax.swing.JLabel();
        lblPanelEstatisticasNumeroUsuariosAutorizados = new javax.swing.JLabel();
        lblPanelEstatiscasUsuariosPendentes = new javax.swing.JLabel();
        lblPanelEstatiscasNumeroUsuariosPendentes = new javax.swing.JLabel();

        lblPanelEstatisticasTotalDeUsuarios.setText("Total de usuários");

        lblPanelEstatisticasNumeroTotalDeUsuarios.setText("NTotalUsuarios");

        lblPanelEstatisticasUsuariosAutorizados.setText("Usuarios Autorizados");

        lblPanelEstatisticasNumeroUsuariosAutorizados.setText("NusuairosAutorizados");

        lblPanelEstatiscasUsuariosPendentes.setText("Usuarios Pendentes");

        lblPanelEstatiscasNumeroUsuariosPendentes.setText("NUsuariosPendentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPanelEstatisticasTotalDeUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPanelEstatisticasNumeroTotalDeUsuarios)
                .addGap(18, 18, 18)
                .addComponent(lblPanelEstatisticasUsuariosAutorizados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPanelEstatisticasNumeroUsuariosAutorizados)
                .addGap(18, 18, 18)
                .addComponent(lblPanelEstatiscasUsuariosPendentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPanelEstatiscasNumeroUsuariosPendentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPanelEstatisticasTotalDeUsuarios)
                    .addComponent(lblPanelEstatiscasUsuariosPendentes)
                    .addComponent(lblPanelEstatisticasUsuariosAutorizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPanelEstatisticasNumeroTotalDeUsuarios)
                    .addComponent(lblPanelEstatisticasNumeroUsuariosAutorizados)
                    .addComponent(lblPanelEstatiscasNumeroUsuariosPendentes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPanelEstatiscasNumeroUsuariosPendentes;
    private javax.swing.JLabel lblPanelEstatiscasUsuariosPendentes;
    private javax.swing.JLabel lblPanelEstatisticasNumeroTotalDeUsuarios;
    private javax.swing.JLabel lblPanelEstatisticasNumeroUsuariosAutorizados;
    private javax.swing.JLabel lblPanelEstatisticasTotalDeUsuarios;
    private javax.swing.JLabel lblPanelEstatisticasUsuariosAutorizados;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblPanelEstatiscasNumeroUsuariosPendentes() {
        return lblPanelEstatiscasNumeroUsuariosPendentes;
    }

    public void setLblPanelEstatiscasNumeroUsuariosPendentes(JLabel lblPanelEstatiscasNumeroUsuariosPendentes) {
        this.lblPanelEstatiscasNumeroUsuariosPendentes = lblPanelEstatiscasNumeroUsuariosPendentes;
    }

    public JLabel getLblPanelEstatiscasUsuariosPendentes() {
        return lblPanelEstatiscasUsuariosPendentes;
    }

    public void setLblPanelEstatiscasUsuariosPendentes(JLabel lblPanelEstatiscasUsuariosPendentes) {
        this.lblPanelEstatiscasUsuariosPendentes = lblPanelEstatiscasUsuariosPendentes;
    }

    public JLabel getLblPanelEstatisticasNumeroTotalDeUsuarios() {
        return lblPanelEstatisticasNumeroTotalDeUsuarios;
    }

    public void setLblPanelEstatisticasNumeroTotalDeUsuarios(JLabel lblPanelEstatisticasNumeroTotalDeUsuarios) {
        this.lblPanelEstatisticasNumeroTotalDeUsuarios = lblPanelEstatisticasNumeroTotalDeUsuarios;
    }

    public JLabel getLblPanelEstatisticasNumeroUsuariosAutorizados() {
        return lblPanelEstatisticasNumeroUsuariosAutorizados;
    }

    public void setLblPanelEstatisticasNumeroUsuariosAutorizados(JLabel lblPanelEstatisticasNumeroUsuariosAutorizados) {
        this.lblPanelEstatisticasNumeroUsuariosAutorizados = lblPanelEstatisticasNumeroUsuariosAutorizados;
    }

    public JLabel getLblPanelEstatisticasTotalDeUsuarios() {
        return lblPanelEstatisticasTotalDeUsuarios;
    }

    public void setLblPanelEstatisticasTotalDeUsuarios(JLabel lblPanelEstatisticasTotalDeUsuarios) {
        this.lblPanelEstatisticasTotalDeUsuarios = lblPanelEstatisticasTotalDeUsuarios;
    }

    public JLabel getLblPanelEstatisticasUsuariosAutorizados() {
        return lblPanelEstatisticasUsuariosAutorizados;
    }

    public void setLblPanelEstatisticasUsuariosAutorizados(JLabel lblPanelEstatisticasUsuariosAutorizados) {
        this.lblPanelEstatisticasUsuariosAutorizados = lblPanelEstatisticasUsuariosAutorizados;
    }
}
