/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author Ayler
 */
public class UserHomeViewSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserHomeViewSwing.class.getName());

    /**
     * Creates new form UserHomeViewSwing
     */
    public UserHomeViewSwing() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(false);
        configurarRodape();
    }
    
     private void configurarRodape() {
  
    getContentPane().removeAll();


    getContentPane().setLayout(new java.awt.BorderLayout());


    javax.swing.JPanel rodape = new javax.swing.JPanel(
            new java.awt.BorderLayout()
    );

 
    java.awt.Font fonteAtual = txtUserLog.getFont();
    txtUserLog.setFont(
            new java.awt.Font(
                    fonteAtual.getName(),
                    java.awt.Font.BOLD,   // NEGRITO
                    fonteAtual.getSize() + 2 // um pouco maior
            )
    );

    txtUserLog.setEditable(false);
    txtUserLog.setBorder(
            javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12)
    );

    rodape.add(txtUserLog, java.awt.BorderLayout.CENTER);

   
    getContentPane().add(rodape, java.awt.BorderLayout.SOUTH);

    revalidate();
    repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserLog = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVisualizarNotificacoesUser = new javax.swing.JMenu();
        mnuEntrada = new javax.swing.JMenuItem();
        mnuLida = new javax.swing.JMenuItem();
        mnuAlterarSenhaUser = new javax.swing.JMenu();
        mnuAlterar = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuVisualizarNotificacoesUser.setText("Notificações");

        mnuEntrada.setText("Caixa de Entrada");
        mnuEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradaActionPerformed(evt);
            }
        });
        mnuVisualizarNotificacoesUser.add(mnuEntrada);

        mnuLida.setText("Lidas");
        mnuVisualizarNotificacoesUser.add(mnuLida);

        jMenuBar1.add(mnuVisualizarNotificacoesUser);

        mnuAlterarSenhaUser.setText("Alterar Senha");

        mnuAlterar.setText("Alterar");
        mnuAlterarSenhaUser.add(mnuAlterar);

        jMenuBar1.add(mnuAlterarSenhaUser);

        btnSair.setText("Sair");

        mnuLogout.setText("Logout");
        btnSair.add(mnuLogout);

        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(txtUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserHomeViewSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlterar;
    private javax.swing.JMenu mnuAlterarSenhaUser;
    private javax.swing.JMenuItem mnuEntrada;
    private javax.swing.JMenuItem mnuLida;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenu mnuVisualizarNotificacoesUser;
    private javax.swing.JTextField txtUserLog;
    // End of variables declaration//GEN-END:variables

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getMnuAlterarSenhaUser() {
        return mnuAlterarSenhaUser;
    }

    public void setMnuAlterarSenhaUser(JMenu mnuAlterarSenhaUser) {
        this.mnuAlterarSenhaUser = mnuAlterarSenhaUser;
    }

    public JMenu getMnuVisualizarNotificacoesUser() {
        return mnuVisualizarNotificacoesUser;
    }

    public void setMnuVisualizarNotificacoesUser(JMenu mnuVisualizarNotificacoesUser) {
        this.mnuVisualizarNotificacoesUser = mnuVisualizarNotificacoesUser;
    }
    
    public JMenuItem getMenuCaixaEntrada() {
    return mnuEntrada;
}

public JMenuItem getMenuLidas() {
    return mnuLida;
}

    public JMenu getBtnSair() {
        return btnSair;
    }

    public void setBtnSair(JMenu btnSair) {
        this.btnSair = btnSair;
    }

    public JMenuItem getMnuEntrada() {
        return mnuEntrada;
    }

    public void setMnuEntrada(JMenuItem mnuEntrada) {
        this.mnuEntrada = mnuEntrada;
    }

    public JMenuItem getMnuLida() {
        return mnuLida;
    }

    public void setMnuLida(JMenuItem mnuLida) {
        this.mnuLida = mnuLida;
    }

    public JMenuItem getMnuLogout() {
        return mnuLogout;
    }

    public void setMnuLogout(JMenuItem mnuLogout) {
        this.mnuLogout = mnuLogout;
    }

    public JTextField getTxtUserLog() {
        return txtUserLog;
    }

    public void setTxtUserLog(JTextField txtUserLog) {
        this.txtUserLog = txtUserLog;
    }

    public JMenuItem getMnuAlterar() {
        return mnuAlterar;
    }

    public void setMnuAlterar(JMenuItem mnuAlterar) {
        this.mnuAlterar = mnuAlterar;
    }

  

}
